version: '3.8'

services:
  # MySQL Database with auto-initialization
  mysql:
    image: mysql:8.0
    container_name: math_ecosystem_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: math_root_2024
      MYSQL_DATABASE: math_ecosystem
      MYSQL_USER: mathuser
      MYSQL_PASSWORD: mathpass_2024
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../architect/04_数据模型设计_实际版.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - math_network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: math_ecosystem_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - math_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Pre-built Application Image
  app:
    image: matheco/k12-math-ecosystem:latest
    container_name: math_ecosystem_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=mysql+pymysql://mathuser:mathpass_2024@mysql:3306/math_ecosystem
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=math_ecosystem_secret_key_2024
      - JWT_SECRET_KEY=jwt_secret_math_2024
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - math_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx with pre-configured settings
  nginx:
    image: nginx:alpine
    container_name: math_ecosystem_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      app:
        condition: service_healthy
    networks:
      - math_network

volumes:
  mysql_data:
  redis_data:
  app_data:
  app_logs:

networks:
  math_network:
    driver: bridge
